### PR TITLE
[FLINK-33859] Support OpenSearch v2

### PR DESCRIPTION
**Pull request by snuyanzin**
The PR adds support for OpenSearch v2

Since there are breaking changes introduced in OpenSearch[1], [2] there is no way for current code in main to be working for both v1 and v2.
For that reason it is now splitted in same way like it is for elastic: one jar for v1, another for v2.

Connector name for v1 is same as before - `opensearch`, for v2 it is `opensearch-2`.

Since v2 is java 11 based there is a java11 maven profile for v2 which makes opensearch connector for v2 building only in case of java 11+.   There are some attempts on OpenSearch side to improve this situation, in case of success building with java8 for OpenSearch v2 could be easily added by removal of that profile.

Also PR  bumps dependency for Flink to 1.18.0. The reason is incompatible changes for ArchUnit which makes the code passing archunit tests either only for 1.17 or only for 1.18., 1.19. 

Also it adds support for java 17

[1] https://github.com/opensearch-project/OpenSearch/pull/9082
[2] https://github.com/opensearch-project/OpenSearch/pull/5902

### CODE REVIEW

**Comment by reta** [comment]
@snuyanzin I think separating v1 and v2 would bring a lot of addition maintenance work, how about trying to use multi-release jar instead? We know 100% that 2.x needs JDK-11, so we could isolate a few key classes that use breaking APIs under `java11` codebase ?

**Comment by snuyanzin** [comment]
I'm curius whether multirelease jar supports cases when for the same Flink cluster there is a necessity to use both Opensearch v1 and OpenSearch v2 connectors and both are built with jdk11 for instance?

**Comment by reta** [comment]
> I'm curious whether multirelease jar supports cases when for the same Flink cluster there is a necessity to use both Opensearch v1 and OpenSearch v2 connectors and both are built with jdk11 for instance?

It is very possible in theory, but would be very difficult to pull off in practice I believe - both clients have overlapping set of classes - and if used with same job, would need quite extensive classloader manipulations

**Comment by snuyanzin** [comment]
yes, I see...

Then it is not clear to me what multi release jar could give us here?
> so we could isolate a few key classes that use breaking APIs under java11 codebase ?

Since currently (main branch) connector is building with jdk8, 11then  IIUC it doesn't solve the issue when connector both for v1 and v2 are building with jdk11.Or did I miss anything?

Here in the PR I also extracted common classes into base module and in v1, v2 related modules are only opensearch api dependent classes

**Comment by reta** [comment]
> Since currently (main branch) connector is building with jdk8, 11 then IIUC it doesn't solve the issue when connector both for v1 and v2 is building with jdk11. Or did I miss anything?

Correct, hence the profiles that we touched upon the other day, jdk-8 - 1.x, jdk-11 - 2.x

> Here in the PR I also extracted common classes into base module and in v1, v2 related modules are only opensearch api dependent classes

I have objections to that (it is a right way to me), I am just suggesting more simpler alternative that we might consider

**Comment by snuyanzin** [comment]
> the profiles that we touched upon the other day, jdk-8 - 1.x, jdk-11 - 2.x

I guess the issue is that so far the build by default is happening for jdk8 and 11, that means that ideally we need to keep it building with jdk11 for v1 as well

**Comment by reta** [comment]
> I guess the issue is that so far the build/test by default is happening for jdk8 and 11, that means that ideally we need to keep it building/testing with jdk11 for v1 as well

Fair point, but we cannot build for jdk8 for 2.x, so it is no win/win in any case sadly

**Comment by snuyanzin** [comment]
at least we could build/test with what it is allowed 
this is what I tried to do and this is how it looks like with this PR
|  Opensearch|  jdk8 | jdk11  | jdk17 (Flink1.18+)   | jdk21 (Flink 1.19+)  |
|---|---|---|---|---|
| v1  | ✅   |✅   | ✅   |✅   |
| v2  | no since OS v2 baseline is jdk11  | ✅  |✅   |✅   |

**Comment by reta** [comment]
> this is what I tried to do and this is how it looks like with this PR

Yep. it looks reasonable

**Comment by snuyanzin** [comment]
@reswqa do you have time to have a look here please?

**Comment by snuyanzin** [comment]
thanks for the feedback @reswqa 

>I just have one question: Since the legacy sink implementation (based on the sink function) is deprecated, why did we need to include it in OpenSearch V2 still?

Here the intention was just to support both versions. The approach was same as for version 1 and for ElasticSearch connector

I guess in fact we need to address this issue with deprecated Sink for both Elastic (6, 7) and OpenSearch(1, 2) connectors.

I would suggest to create a dedicated follow up task for that, WDYT?

**Comment by reta** [comment]
> I would suggest to create a dedicated follow up task for that, WDYT?

@snuyanzin fyi, we have https://github.com/apache/flink-connector-opensearch/pull/5 open

**Review by reta — APPROVED** [review]
Thanks @snuyanzin !

**Comment by joshbsemperis** [comment]
Can this be resolved and pushed? Is there a reason why it hasnt?

**Comment by snuyanzin** [comment]
first this should be  reviewed/approved/merged 
https://github.com/apache/flink-connector-opensearch/pull/42
then we could continue with this PR

**Comment by joshbsemperis** [comment]
can we now continue with this @reta  @reswqa  @snuyanzin

**Comment by snuyanzin** [comment]
this is in my todo list for today/tomorrow

**Comment by snuyanzin** [comment]
Thanks for the review
I solved the conflicts and added profiles to simplify releasing separately for v1 and v2 as was mentioned in ml

**Comment by stanb** [comment]
where can i download opensearch 2 compatible flink sql connector jar?

**Comment by snuyanzin** [comment]
It is in voting stage
you can find links to artifacts (including jars for os v2) in corresponding email thread
https://lists.apache.org/thread/by44cdpfv6p9394vwxhh1vzh3rfskzms

**Comment by snuyanzin** [comment]
>I mean the built jar file.
I tried to build it myself and use with my jobs

if you open the email thread https://lists.apache.org/thread/by44cdpfv6p9394vwxhh1vzh3rfskzms

you will see 
>* the official Apache source release to be deployed to dist.apache.org [2],
...
[2]
https://dist.apache.org/repos/dist/dev/flink/flink-connector-opensearch-2.0.0-rc1

and this is a link to the folder  containing jars, however again these jars are only RC, not the release yet

**Comment by stanb** [comment]
there is only `tgz` that contains sources. there is no compiled `jar`.

**Comment by stanb** [comment]
With this jar i get another error:
```
2024-05-22 15:57:26
org.apache.flink.runtime.JobException: Recovery is suppressed by NoRestartBackoffTimeStrategy
	at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.handleFailure(ExecutionFailureHandler.java:176)
	at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.getFailureHandlingResult(ExecutionFailureHandler.java:107)
	at org.apache.flink.runtime.scheduler.DefaultScheduler.recordTaskFailure(DefaultScheduler.java:285)
	at org.apache.flink.runtime.scheduler.DefaultScheduler.handleTaskFailure(DefaultScheduler.java:276)
	at org.apache.flink.runtime.scheduler.DefaultScheduler.onTaskFailed(DefaultScheduler.java:269)
	at org.apache.flink.runtime.scheduler.SchedulerBase.onTaskExecutionStateUpdate(SchedulerBase.java:764)
	at org.apache.flink.runtime.scheduler.SchedulerBase.updateTaskExecutionState(SchedulerBase.java:741)
	at org.apache.flink.runtime.scheduler.SchedulerNG.updateTaskExecutionState(SchedulerNG.java:83)
	at org.apache.flink.runtime.jobmaster.JobMaster.updateTaskExecutionState(JobMaster.java:488)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.flink.runtime.rpc.pekko.PekkoRpcActor.lambda$handleRpcInvocation$1(PekkoRpcActor.java:309)
	at org.apache.flink.runtime.concurrent.ClassLoadingUtils.runWithContextClassLoader(ClassLoadingUtils.java:83)
	at org.apache.flink.runtime.rpc.pekko.PekkoRpcActor.handleRpcInvocation(PekkoRpcActor.java:307)
	at org.apache.flink.runtime.rpc.pekko.PekkoRpcActor.handleRpcMessage(PekkoRpcActor.java:222)
	at org.apache.flink.runtime.rpc.pekko.FencedPekkoRpcActor.handleRpcMessage(FencedPekkoRpcActor.java:85)
	at org.apache.flink.runtime.rpc.pekko.PekkoRpcActor.handleMessage(PekkoRpcActor.java:168)
	at org.apache.pekko.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:33)
	at org.apache.pekko.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:29)
	at scala.PartialFunction.applyOrElse(PartialFunction.scala:127)
	at scala.PartialFunction.applyOrElse$(PartialFunction.scala:126)
	at org.apache.pekko.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:29)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:175)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
	at org.apache.pekko.actor.Actor.aroundReceive(Actor.scala:547)
	at org.apache.pekko.actor.Actor.aroundReceive$(Actor.scala:545)
	at org.apache.pekko.actor.AbstractActor.aroundReceive(AbstractActor.scala:229)
	at org.apache.pekko.actor.ActorCell.receiveMessage(ActorCell.scala:590)
	at org.apache.pekko.actor.ActorCell.invoke(ActorCell.scala:557)
	at org.apache.pekko.dispatch.Mailbox.processMailbox(Mailbox.scala:280)
	at org.apache.pekko.dispatch.Mailbox.run(Mailbox.scala:241)
	at org.apache.pekko.dispatch.Mailbox.exec(Mailbox.scala:253)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.ExceptionInInitializerError
	at org.apache.flink.opensearch2.shaded.org.opensearch.transport.RemoteClusterService.lambda$static$1(RemoteClusterService.java:123)
	at org.apache.flink.opensearch2.shaded.org.opensearch.common.settings.Setting.affixKeySetting(Setting.java:2837)
	at org.apache.flink.opensearch2.shaded.org.opensearch.transport.RemoteClusterService.<clinit>(RemoteClusterService.java:120)
	at org.apache.flink.opensearch2.shaded.org.opensearch.node.Node.<clinit>(Node.java:318)
	at org.apache.flink.opensearch2.shaded.org.opensearch.common.util.concurrent.OpenSearchExecutors.threadName(OpenSearchExecutors.java:361)
	at org.apache.flink.opensearch2.shaded.org.opensearch.common.util.concurrent.OpenSearchExecutors.daemonThreadFactory(OpenSearchExecutors.java:375)
	at org.apache.flink.opensearch2.shaded.org.opensearch.threadpool.Scheduler.initScheduler(Scheduler.java:73)
	at org.apache.flink.opensearch2.shaded.org.opensearch.action.bulk.BulkProcessor.builder(BulkProcessor.java:263)
	at org.apache.flink.connector.opensearch.sink.Opensearch2Writer.createBulkProcessor(Opensearch2Writer.java:166)
	at org.apache.flink.connector.opensearch.sink.Opensearch2Writer.<init>(Opensearch2Writer.java:113)
	at org.apache.flink.connector.opensearch.sink.Opensearch2Sink.createWriter(Opensearch2Sink.java:95)
	at org.apache.flink.streaming.runtime.operators.sink.StatelessSinkWriterStateHandler.createWriter(StatelessSinkWriterStateHandler.java:39)
	at org.apache.flink.streaming.runtime.operators.sink.SinkWriterOperator.initializeState(SinkWriterOperator.java:149)
	at org.apache.flink.streaming.api.operators.StreamOperatorStateHandler.initializeOperatorState(StreamOperatorStateHandler.java:122)
	at org.apache.flink.streaming.api.operators.AbstractStreamOperator.initializeState(AbstractStreamOperator.java:274)
	at org.apache.flink.streaming.runtime.tasks.RegularOperatorChain.initializeStateAndOpenOperators(RegularOperatorChain.java:106)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restoreGates(StreamTask.java:753)
	at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$1.call(StreamTaskActionExecutor.java:55)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restoreInternal(StreamTask.java:728)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restore(StreamTask.java:693)
	at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:953)
	at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:922)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:746)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:562)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at org.apache.flink.opensearch2.shaded.org.opensearch.common.settings.Setting.arrayToParsableString(Setting.java:2373)
	at org.apache.flink.opensearch2.shaded.org.opensearch.common.settings.Setting$ListSetting.lambda$new$0(Setting.java:2405)
	at org.apache.flink.opensearch2.shaded.org.opensearch.common.settings.Setting$ListSetting.innerGetRaw(Setting.java:2416)
	at org.apache.flink.opensearch2.shaded.org.opensearch.common.settings.Setting.getRaw(Setting.java:549)
	at org.apache.flink.opensearch2.shaded.org.opensearch.common.settings.Setting.lambda$listSetting$37(Setting.java:2300)
	at org.apache.flink.opensearch2.shaded.org.opensearch.common.settings.Setting.listSetting(Setting.java:2340)
	at org.apache.flink.opensearch2.shaded.org.opensearch.common.settings.Setting.listSetting(Setting.java:2329)
	at org.apache.flink.opensearch2.shaded.org.opensearch.common.settings.Setting.listSetting(Setting.java:2300)
	at org.apache.flink.opensearch2.shaded.org.opensearch.transport.TransportSettings.<clinit>(TransportSettings.java:68)
	... 25 more
```

**Comment by snuyanzin** [comment]
could you provide a minimum reproducing test for that?
I guess something like IT test

**Comment by aniruddhj** [comment]
@snuyanzin I am having a similar issue. We have Flink 1.19.1 and Opensearch 2.19.0 installed on our system. I have added the `flink-sql-connector-opensearch2-2.0.0-1.19.jar` (downloaded from [maven](https://repo.maven.apache.org/maven2/org/apache/flink/flink-sql-connector-opensearch2/2.0.0-1.19/))
```
2025-03-26 21:53:28,183 INFO  org.apache.flink.runtime.entrypoint.ClusterEntrypoint        [] -  Classpath: /opt/flink/lib/flink-sql-connector-opensearch2-2.0.0-1.19.jar::::
```
From the latest code I could see the [`opensearch.version` is `2.13.0`](https://github.com/apache/flink-connector-opensearch/blob/11cde7b1526b220e2836b0492fd97bcc3c81d3bd/flink-connector-opensearch2/pom.xml#L39) hence I installed a 2.13.0 Opensearch. 
Even with all the above changes when I run the `.bin/sql-client.sh` and follow steps from  https://opensearch.org/blog/OpenSearch-Flink-Connector/ it ends in error 
```
2025-03-26 21:59:33,352 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph       [] - myUserTable[3]: Writer (1/1) (8bd01e472d186428f97d3b2b608c8985_306d8342cb5b2ad8b53f1be57f65bee8_0_0) switched from INITIALIZING to FAILED on 10.254.16.48:6122-8a0669 @ 10.254.16.48 (dataPort=41903).
java.lang.ExceptionInInitializerError: null
	at java.lang.J9VMInternals.recordInitializationFailure(Unknown Source) ~[?:?]
	at org.apache.flink.opensearch2.shaded.org.opensearch.transport.RemoteClusterService.lambda$static$1(RemoteClusterService.java:123) ~[flink-sql-connector-opensearch2-2.0.0-1.19.jar:2.0.0-1.19]
	at org.apache.flink.opensearch2.shaded.org.opensearch.common.settings.Setting.affixKeySetting(Setting.java:2837) ~[flink-sql-connector-opensearch2-2.0.0-1.19.jar:2.0.0-1.19]
	at org.apache.flink.opensearch2.shaded.org.opensearch.transport.RemoteClusterService.<clinit>(RemoteClusterService.java:120) ~[flink-sql-connector-opensearch2-2.0.0-1.19.jar:2.0.0-1.19]
	at org.apache.flink.opensearch2.shaded.org.opensearch.node.Node.<clinit>(Node.java:318) ~[flink-sql-connector-opensearch2-2.0.0-1.19.jar:2.0.0-1.19]
	at org.apache.flink.opensearch2.shaded.org.opensearch.common.util.concurrent.OpenSearchExecutors.threadName(OpenSearchExecutors.java:361) ~[flink-sql-connector-opensearch2-2.0.0-1.19.jar:2.0.0-1.19]
	at org.apache.flink.opensearch2.shaded.org.opensearch.common.util.concurrent.OpenSearchExecutors.daemonThreadFactory(OpenSearchExecutors.java:375) ~[flink-sql-connector-opensearch2-2.0.0-1.19.jar:2.0.0-1.19]
	at org.apache.flink.opensearch2.shaded.org.opensearch.threadpool.Scheduler.initScheduler(Scheduler.java:73) ~[flink-sql-connector-opensearch2-2.0.0-1.19.jar:2.0.0-1.19]
	at org.apache.flink.opensearch2.shaded.org.opensearch.action.bulk.BulkProcessor.builder(BulkProcessor.java:263) ~[flink-sql-connector-opensearch2-2.0.0-1.19.jar:2.0.0-1.19]
	at org.apache.flink.connector.opensearch.sink.Opensearch2Writer.createBulkProcessor(Opensearch2Writer.java:166) ~[flink-sql-connector-opensearch2-2.0.0-1.19.jar:2.0.0-1.19]
	at org.apache.flink.connector.opensearch.sink.Opensearch2Writer.<init>(Opensearch2Writer.java:113) ~[flink-sql-connector-opensearch2-2.0.0-1.19.jar:2.0.0-1.19]
	at org.apache.flink.connector.opensearch.sink.Opensearch2Sink.createWriter(Opensearch2Sink.java:95) ~[flink-sql-connector-opensearch2-2.0.0-1.19.jar:2.0.0-1.19]
	at org.apache.flink.api.connector.sink2.Sink.createWriter(Sink.java:77) ~[flink-dist-1.19.1.jar:1.19.1]
	at org.apache.flink.streaming.runtime.operators.sink.StatelessSinkWriterStateHandler.createWriter(StatelessSinkWriterStateHandler.java:39) ~[flink-dist-1.19.1.jar:1.19.1]
	at org.apache.flink.streaming.runtime.operators.sink.SinkWriterOperator.initializeState(SinkWriterOperator.java:148) ~[flink-dist-1.19.1.jar:1.19.1]
	at org.apache.flink.streaming.api.operators.StreamOperatorStateHandler.initializeOperatorState(StreamOperatorStateHandler.java:134) ~[flink-dist-1.19.1.jar:1.19.1]
	at org.apache.flink.streaming.api.operators.AbstractStreamOperator.initializeState(AbstractStreamOperator.java:286) ~[flink-dist-1.19.1.jar:1.19.1]
	at org.apache.flink.streaming.runtime.tasks.RegularOperatorChain.initializeStateAndOpenOperators(RegularOperatorChain.java:106) ~[flink-dist-1.19.1.jar:1.19.1]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restoreStateAndGates(StreamTask.java:799) ~[flink-dist-1.19.1.jar:1.19.1]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.lambda$restoreInternal$3(StreamTask.java:753) ~[flink-dist-1.19.1.jar:1.19.1]
	at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$1.call(StreamTaskActionExecutor.java:55) ~[flink-dist-1.19.1.jar:1.19.1]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restoreInternal(StreamTask.java:753) ~[flink-dist-1.19.1.jar:1.19.1]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restore(StreamTask.java:712) ~[flink-dist-1.19.1.jar:1.19.1]
	at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:958) ~[flink-dist-1.19.1.jar:1.19.1]
	at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:927) ~[flink-dist-1.19.1.jar:1.19.1]
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:751) ~[flink-dist-1.19.1.jar:1.19.1]
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:566) ~[flink-dist-1.19.1.jar:1.19.1]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.NullPointerException
	at org.apache.flink.opensearch2.shaded.org.opensearch.common.settings.Setting.arrayToParsableString(Setting.java:2373) ~[flink-sql-connector-opensearch2-2.0.0-1.19.jar:2.0.0-1.19]
	at org.apache.flink.opensearch2.shaded.org.opensearch.common.settings.Setting$ListSetting.lambda$new$0(Setting.java:2405) ~[flink-sql-connector-opensearch2-2.0.0-1.19.jar:2.0.0-1.19]
	at org.apache.flink.opensearch2.shaded.org.opensearch.common.settings.Setting$ListSetting.innerGetRaw(Setting.java:2416) ~[flink-sql-connector-opensearch2-2.0.0-1.19.jar:2.0.0-1.19]
	at org.apache.flink.opensearch2.shaded.org.opensearch.common.settings.Setting.getRaw(Setting.java:549) ~[flink-sql-connector-opensearch2-2.0.0-1.19.jar:2.0.0-1.19]
	at org.apache.flink.opensearch2.shaded.org.opensearch.common.settings.Setting.lambda$listSetting$37(Setting.java:2300) ~[flink-sql-connector-opensearch2-2.0.0-1.19.jar:2.0.0-1.19]
	at org.apache.flink.opensearch2.shaded.org.opensearch.common.settings.Setting.listSetting(Setting.java:2340) ~[flink-sql-connector-opensearch2-2.0.0-1.19.jar:2.0.0-1.19]
	at org.apache.flink.opensearch2.shaded.org.opensearch.common.settings.Setting.listSetting(Setting.java:2329) ~[flink-sql-connector-opensearch2-2.0.0-1.19.jar:2.0.0-1.19]
	at org.apache.flink.opensearch2.shaded.org.opensearch.common.settings.Setting.listSetting(Setting.java:2300) ~[flink-sql-connector-opensearch2-2.0.0-1.19.jar:2.0.0-1.19]
	at org.apache.flink.opensearch2.shaded.org.opensearch.transport.TransportSettings.<clinit>(TransportSettings.java:68) ~[flink-sql-connector-opensearch2-2.0.0-1.19.jar:2.0.0-1.19]
```
and 
```
2025-03-26 22:00:03,509 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph       [] - myUserTable[3]: Writer (1/1) (8bd01e472d186428f97d3b2b608c8985_306d8342cb5b2ad8b53f1be57f65bee8_0_1) switched from INITIALIZING to FAILED on 10.254.16.48:6122-8a0669 @ 10.254.16.48 (dataPort=41903).
java.lang.NoClassDefFoundError: org.apache.flink.opensearch2.shaded.org.opensearch.node.Node (initialization failure)
	at java.lang.J9VMInternals.initializationAlreadyFailed(Unknown Source) ~[?:?]
	at org.apache.flink.opensearch2.shaded.org.opensearch.common.util.concurrent.OpenSearchExecutors.threadName(OpenSearchExecutors.java:361) ~[flink-sql-connector-opensearch2-2.0.0-1.19.jar:2.0.0-1.19]
	at org.apache.flink.opensearch2.shaded.org.opensearch.common.util.concurrent.OpenSearchExecutors.daemonThreadFactory(OpenSearchExecutors.java:375) ~[flink-sql-connector-opensearch2-2.0.0-1.19.jar:2.0.0-1.19]
	at org.apache.flink.opensearch2.shaded.org.opensearch.threadpool.Scheduler.initScheduler(Scheduler.java:73) ~[flink-sql-connector-opensearch2-2.0.0-1.19.jar:2.0.0-1.19]
	at org.apache.flink.opensearch2.shaded.org.opensearch.action.bulk.BulkProcessor.builder(BulkProcessor.java:263) ~[flink-sql-connector-opensearch2-2.0.0-1.19.jar:2.0.0-1.19]
	at org.apache.flink.connector.opensearch.sink.Opensearch2Writer.createBulkProcessor(Opensearch2Writer.java:166) ~[flink-sql-connector-opensearch2-2.0.0-1.19.jar:2.0.0-1.19]
	at org.apache.flink.connector.opensearch.sink.Opensearch2Writer.<init>(Opensearch2Writer.java:113) ~[flink-sql-connector-opensearch2-2.0.0-1.19.jar:2.0.0-1.19]
	at org.apache.flink.connector.opensearch.sink.Opensearch2Sink.createWriter(Opensearch2Sink.java:95) ~[flink-sql-connector-opensearch2-2.0.0-1.19.jar:2.0.0-1.19]
	at org.apache.flink.api.connector.sink2.Sink.createWriter(Sink.java:77) ~[flink-dist-1.19.1.jar:1.19.1]
	at org.apache.flink.streaming.runtime.operators.sink.StatelessSinkWriterStateHandler.createWriter(StatelessSinkWriterStateHandler.java:39) ~[flink-dist-1.19.1.jar:1.19.1]
	at org.apache.flink.streaming.runtime.operators.sink.SinkWriterOperator.initializeState(SinkWriterOperator.java:148) ~[flink-dist-1.19.1.jar:1.19.1]
	at org.apache.flink.streaming.api.operators.StreamOperatorStateHandler.initializeOperatorState(StreamOperatorStateHandler.java:134) ~[flink-dist-1.19.1.jar:1.19.1]
	at org.apache.flink.streaming.api.operators.AbstractStreamOperator.initializeState(AbstractStreamOperator.java:286) ~[flink-dist-1.19.1.jar:1.19.1]
	at org.apache.flink.streaming.runtime.tasks.RegularOperatorChain.initializeStateAndOpenOperators(RegularOperatorChain.java:106) ~[flink-dist-1.19.1.jar:1.19.1]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restoreStateAndGates(StreamTask.java:799) ~[flink-dist-1.19.1.jar:1.19.1]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.lambda$restoreInternal$3(StreamTask.java:753) ~[flink-dist-1.19.1.jar:1.19.1]
	at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$1.call(StreamTaskActionExecutor.java:55) ~[flink-dist-1.19.1.jar:1.19.1]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restoreInternal(StreamTask.java:753) ~[flink-dist-1.19.1.jar:1.19.1]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restore(StreamTask.java:712) ~[flink-dist-1.19.1.jar:1.19.1]
	at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:958) ~[flink-dist-1.19.1.jar:1.19.1]
	at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:927) ~[flink-dist-1.19.1.jar:1.19.1]
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:751) ~[flink-dist-1.19.1.jar:1.19.1]
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:566) ~[flink-dist-1.19.1.jar:1.19.1]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError
	at java.lang.J9VMInternals.recordInitializationFailure(Unknown Source) ~[?:?]
	at org.apache.flink.opensearch2.shaded.org.opensearch.transport.RemoteClusterService.lambda$static$1(RemoteClusterService.java:123) ~[flink-sql-connector-opensearch2-2.0.0-1.19.jar:2.0.0-1.19]
	at org.apache.flink.opensearch2.shaded.org.opensearch.common.settings.Setting.affixKeySetting(Setting.java:2837) ~[flink-sql-connector-opensearch2-2.0.0-1.19.jar:2.0.0-1.19]
	at org.apache.flink.opensearch2.shaded.org.opensearch.transport.RemoteClusterService.<clinit>(RemoteClusterService.java:120) ~[flink-sql-connector-opensearch2-2.0.0-1.19.jar:2.0.0-1.19]
	at org.apache.flink.opensearch2.shaded.org.opensearch.node.Node.<clinit>(Node.java:318) ~[flink-sql-connector-opensearch2-2.0.0-1.19.jar:2.0.0-1.19]
	... 23 more
Caused by: java.lang.NullPointerException
	at org.apache.flink.opensearch2.shaded.org.opensearch.common.settings.Setting.arrayToParsableString(Setting.java:2373) ~[flink-sql-connector-opensearch2-2.0.0-1.19.jar:2.0.0-1.19]
	at org.apache.flink.opensearch2.shaded.org.opensearch.common.settings.Setting$ListSetting.lambda$new$0(Setting.java:2405) ~[flink-sql-connector-opensearch2-2.0.0-1.19.jar:2.0.0-1.19]
	at org.apache.flink.opensearch2.shaded.org.opensearch.common.settings.Setting$ListSetting.innerGetRaw(Setting.java:2416) ~[flink-sql-connector-opensearch2-2.0.0-1.19.jar:2.0.0-1.19]
	at org.apache.flink.opensearch2.shaded.org.opensearch.common.settings.Setting.getRaw(Setting.java:549) ~[flink-sql-connector-opensearch2-2.0.0-1.19.jar:2.0.0-1.19]
	at org.apache.flink.opensearch2.shaded.org.opensearch.common.settings.Setting.lambda$listSetting$37(Setting.java:2300) ~[flink-sql-connector-opensearch2-2.0.0-1.19.jar:2.0.0-1.19]
	at org.apache.flink.opensearch2.shaded.org.opensearch.common.settings.Setting.listSetting(Setting.java:2340) ~[flink-sql-connector-opensearch2-2.0.0-1.19.jar:2.0.0-1.19]
	at org.apache.flink.opensearch2.shaded.org.opensearch.common.settings.Setting.listSetting(Setting.java:2329) ~[flink-sql-connector-opensearch2-2.0.0-1.19.jar:2.0.0-1.19]
	at org.apache.flink.opensearch2.shaded.org.opensearch.common.settings.Setting.listSetting(Setting.java:2300) ~[flink-sql-connector-opensearch2-2.0.0-1.19.jar:2.0.0-1.19]
	at org.apache.flink.opensearch2.shaded.org.opensearch.transport.TransportSettings.<clinit>(TransportSettings.java:68) ~[flink-sql-connector-opensearch2-2.0.0-1.19.jar:2.0.0-1.19]
	at org.apache.flink.opensearch2.shaded.org.opensearch.transport.RemoteClusterService.lambda$static$1(RemoteClusterService.java:123) ~[flink-sql-connector-opensearch2-2.0.0-1.19.jar:2.0.0-1.19]
	at org.apache.flink.opensearch2.shaded.org.opensearch.common.settings.Setting.affixKeySetting(Setting.java:2837) ~[flink-sql-connector-opensearch2-2.0.0-1.19.jar:2.0.0-1.19]
	at org.apache.flink.opensearch2.shaded.org.opensearch.transport.RemoteClusterService.<clinit>(RemoteClusterService.java:120) ~[flink-sql-connector-opensearch2-2.0.0-1.19.jar:2.0.0-1.19]
	at org.apache.flink.opensearch2.shaded.org.opensearch.node.Node.<clinit>(Node.java:318) ~[flink-sql-connector-opensearch2-2.0.0-1.19.jar:2.0.0-1.19]
	... 23 more
```

My understanding with the second part of the issue is the class is not being available at the runtime. Is there something that needs to provided additional to the jar or is this an issue with sql-client? Thanks!

**Pull request merged**
